### Create user valid

POST http://localhost:8080/api/users
Content-Type: application/json
Accept: application/json

{
  "id": "USR00001",
  "name" : "Jono Suparjono",
  "email" : "jono@email.com",
  "password" : "Password123",
  "gender" : "Male",
  "phone" : "081283027346"
}


### Create user invalid


POST http://localhost:8080/api/users
Content-Type: application/json
Accept: application/json

{
  "id": "USR00002",
  "name" : "Juki Suparjuki",
  "email" : "juki@email.com",
  "password" : "pass",
  "gender" : "",
  "phone" : "081283027338"
}


### Get user found

GET http://localhost:8080/api/users/USR00001
Accept: application/json


### Get user not found

GET http://localhost:8080/api/users/USRAU292
Accept: application/json


### Update user valid

PUT http://localhost:8080/api/users/USR00001
Content-Type: application/json
Accept: application/json

{
  "name" : "Jono Sujono",
  "email" : "jono@email.com",
  "gender" : "Male",
  "phone" : "081212345678"
}


### Update user not valid

PUT http://localhost:8080/api/users/USRAU292
Content-Type: application/json
Accept: application/json

{
  "name" : "",
  "email" : "jono@email.com",
  "gender" : "Male",
  "phone" : "081212345678"
}


### Delete user found

DELETE http://localhost:8080/api/users/USR00002
Accept: application/json


### Delete user not found

DELETE http://localhost:8080/api/users/
Accept: application/json


### Get list user

GET http://localhost:8080/api/users?page=0&size=10
Accept: application/json


### Change password user

PUT http://localhost:8080/api/users/USR00001/changepassword
Content-Type: application/json
Accept: application/json

{
  "oldPassword" : "Password123",
  "newPassword" : "Secret123"
}
